packages:
  - packages/**
  - plugins/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'

catalog:
  '@moeru/std': 0.1.0-beta.7
  '@proj-airi/drizzle-duckdb-wasm': ^0.4.28
  '@xsai-ext/providers-cloud': ^0.3.4
  '@xsai-ext/providers-local': ^0.3.4
  '@xsai-ext/shared-providers': ^0.3.4
  '@xsai/embed': ^0.3.4
  '@xsai/generate-speech': ^0.3.4
  '@xsai/generate-text': 0.3.4
  '@xsai/generate-transcription': ^0.3.4
  '@xsai/model': ^0.3.4
  '@xsai/shared': ^0.3.4
  '@xsai/shared-chat': ^0.3.4
  '@xsai/stream-text': ^0.3.4
  '@xsai/tool': ^0.3.4
  '@xsai/utils-chat': ^0.3.4
  xsschema: ^0.3.4

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.0.12
